# Generated by Django 3.2.13 on 2022-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
